Add ctl command upgrade

diff --git a/config/templates/package-scripts/preinst.erb b/config/templates/package-scripts/preinst.erb
--- a/config/templates/package-scripts/preinst.erb
+++ b/config/templates/package-scripts/preinst.erb
@@ -1,7 +1,48 @@
-#!/bin/bash
-#
-# Perform necessary unifiedpush setup steps
-# before package is installed.
-#
+#!/bin/sh
+# unifiedpush-server pre-install script
 
-echo "You're about to install unifiedpush!"
+DEST_DIR=<%= install_dir %>
+
+skip_migrations_file=/etc/unifiedpush/skip-auto-migrations
+
+main() {
+  if [ -e "${skip_migrations_file}" ] ; then
+    # The user wants us to do nothing
+    return
+  fi
+
+  if [ -d ${DEST_DIR}/service/unifiedpush-server ] ; then
+    #notify "Backing up Unifiedpush Server SQL database (excluding configuration, uploads)"
+    #if ! ${DEST_DIR}/bin/unifiedpush-backup.sh ; then
+    #  notify
+    #  notify "Backup failed! If you want to skip this backup, run the following command and"
+    #  notify "try again:"
+    #  notify
+    #  notify "  sudo touch ${skip_migrations_file}"
+    #  notify
+    #  exit 1
+    #fi
+  fi
+}
+
+notify() {
+  echo "unifiedpush-server preinstall: $1"
+}
+
+if [ -n "${UNIFIEDPUSH_DEBUG}" ] ; then
+  notify "debug: arguments: $@"
+fi
+
+case "$1" in
+  2)
+    # Looks like an RPM upgrade
+    main
+    ;;
+  upgrade)
+    # Looks like a DEB upgrade
+    main
+    ;;
+  *)
+    # This is not an upgrade, nothing to do.
+    ;;
+esac
